#PBS -l nodes=1:ppn=20
#PBS -l walltime=48:00:00
#PBS -A open
#PBS -o /storage/home/hqd1/NeuroProject/log/simulation-${it}.log
#PBS -j oe
#PBS -m abe
#PBS -M hqd1@psu.edu
#PBS -l mem=100gb
cd /storage/home/hqd1/NeuroProject/

echo " "
echo " "
echo "Job started on `hostname` at `date`"
echo " "

module load r/3.5.2
Rscript lipschitz_simulation.R $it $positive 


echo " "
echo "Job Ended at `date`"
echo " "
